imports:
    - { resource: config_dev.yml }
    - { resource: "@MooFlashCardBundle/Resources/config/config_test.yml" }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
#    
#doctrine:
#    dbal:
#        dbname: symfony_testdb
